name: CSV
language: python
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: airpassengers
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
